extends:
  - "@postmates"
  - plugin:jest/recommended


parser: babel-eslint

env:
  jest/globals: true

plugins:
  - jest
  - typescript

globals:
  window: true
  document: true
  __DEV__: true
  __ENV__: true

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .tsx
        - .ts
    webpack:
      config:
        resolve:
          extensions:
            - .js
            - .jsx
            - .tsx
            - .ts

rules:
  import/prefer-default-export: off
  arrow-parens: off
  import/no-webpack-loader-syntax: off
  no-mixed-operators: off
  no-throw-literal: off
  no-restricted-syntax: off
  react/style-prop-object: off
  no-prototype-builtins: off
  react/no-array-index-key: off
  react/sort-comp: off
  no-continue: off
  
  default-case: off

  bfe/no-default-emotion-import: error

  react/jsx-filename-extension:
    - error
    - extensions:
      - .jsx
      - .tsx
  import/extensions:
    - error
    - always
    - js: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - '**/*.spec.js'
      - '**/*.spec.jsx'
      - '**/*.spec.ts'
      - '**/*.spec.tsx'
overrides:
  - parser: "typescript-eslint-parser"
    files:
      - '*.ts'
      - '*.tsx'
    rules:
      no-useless-constructor: off
      no-undef: off
      no-unused-vars: off
      typescript/no-unused-vars: off
      react/prop-types: off
      arrow-parens: error
      no-param-reassign: off
      space-infix-ops: off
      import/export: off
      import/no-duplicates: off
      no-use-before-define: off
      no-shadow: off
      require-yield: off
      consistent-return: off
      typescript/adjacent-overload-signatures: error
      typescript/member-delimiter-style: error
      typescript/no-angle-bracket-type-assertion: error
      typescript/type-annotation-spacing: error
      bfe/no-default-emotion-import: off
