language: node_js
node_js:
  - 'node'
script:
  - yarn lint
  - yarn test
  - yarn build
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master